//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ayarlar
    {
        public int Id { get; set; }
        public int GelenEvrakEkGun { get; set; }
        public int GidenEvrakEkGun { get; set; }
        public Nullable<bool> GelenEvrakKontrol { get; set; }
        public Nullable<bool> GidenEvrakKontrol { get; set; }
        public Nullable<bool> DaimiAramaTKontrol { get; set; }
        public int DaimiAramaEkGun { get; set; }
        public Nullable<int> GelenEvrakKontrolSuresi { get; set; }
        public Nullable<int> GidenEvrakKontrolSuresi { get; set; }
        public Nullable<int> DaimiAramaKontrolSuresi { get; set; }
    }
}
