//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ETSEntities : DbContext
    {
        public ETSEntities()
            : base("name=ETSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ArsivGelenGiden> ArsivGelenGiden { get; set; }
        public DbSet<Ayarlar> Ayarlar { get; set; }
        public DbSet<Baslik> Baslik { get; set; }
        public DbSet<Birimler> Birimler { get; set; }
        public DbSet<DaimiArastirmaTutanaklari> DaimiArastirmaTutanaklari { get; set; }
        public DbSet<EvrakiCikaranMakam> EvrakiCikaranMakam { get; set; }
        public DbSet<EvrakKategori> EvrakKategori { get; set; }
        public DbSet<GelenEvrak> GelenEvrak { get; set; }
        public DbSet<GidenEvrak> GidenEvrak { get; set; }
        public DbSet<GizlilikDerecesi> GizlilikDerecesi { get; set; }
        public DbSet<GonderdigiMakam> GonderdigiMakam { get; set; }
        public DbSet<GuvenlikNoOncelikDerecesi> GuvenlikNoOncelikDerecesi { get; set; }
        public DbSet<KanunMaddeleri> KanunMaddeleri { get; set; }
        public DbSet<KimlikBilgileri> KimlikBilgileri { get; set; }
        public DbSet<Komutanliklar> Komutanliklar { get; set; }
        public DbSet<MuzekkereCinsleri> MuzekkereCinsleri { get; set; }
        public DbSet<MuzekkereIcmalDefteri> MuzekkereIcmalDefteri { get; set; }
        public DbSet<OlayDurumu> OlayDurumu { get; set; }
        public DbSet<OlaylarBilgisi> OlaylarBilgisi { get; set; }
        public DbSet<OlayYerleri> OlayYerleri { get; set; }
        public DbSet<Periyotlar> Periyotlar { get; set; }
        public DbSet<Personel> Personel { get; set; }
        public DbSet<Subeler> Subeler { get; set; }
        public DbSet<Suclar> Suclar { get; set; }
        public DbSet<Tasnifler> Tasnifler { get; set; }
        public DbSet<TempOlaylar> TempOlaylar { get; set; }
        public DbSet<ZimmetDefteri> ZimmetDefteri { get; set; }
    }
}
