//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvrakKategori
    {
        public EvrakKategori()
        {
            this.ZimmetDefteri = new HashSet<ZimmetDefteri>();
        }
    
        public int Id { get; set; }
        public string Kategori { get; set; }
    
        public virtual ICollection<ZimmetDefteri> ZimmetDefteri { get; set; }
    }
}
