//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class GelenEvrak
    {
        public GelenEvrak()
        {
            this.ZimmetDefteri = new HashSet<ZimmetDefteri>();
        }
    
        public long Id { get; set; }
        public long EvrakKayitNo { get; set; }
        public System.DateTime EvrakKayitTarihi { get; set; }
        public int EvrakiCikaranMakamId { get; set; }
        public System.DateTime TarihTSG { get; set; }
        public string DosyaNoKonusu { get; set; }
        public int GizlilikDerecesiId { get; set; }
        public int GuvenlikNoOncelikDerecesiId { get; set; }
        public string Aciklama { get; set; }
        public int Durum { get; set; }
        public System.DateTime EvrakSonTarihi { get; set; }
        public Nullable<long> ZimmetId { get; set; }
        public int OlayDurumuId { get; set; }
        public int PersonelId { get; set; }
        public Nullable<int> OlayYeriId { get; set; }
        public bool Arsivlendi { get; set; }
    
        public virtual EvrakiCikaranMakam EvrakiCikaranMakam { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual ICollection<ZimmetDefteri> ZimmetDefteri { get; set; }
        public virtual OlayYerleri OlayYerleri { get; set; }
        public virtual GizlilikDerecesi GizlilikDerecesi { get; set; }
        public virtual GuvenlikNoOncelikDerecesi GuvenlikNoOncelikDerecesi { get; set; }
        public virtual OlayDurumu OlayDurumu { get; set; }
        public virtual ZimmetDefteri ZimmetDefteri1 { get; set; }
    }
}
