//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class KimlikBilgileri
    {
        public int Id { get; set; }
        public Nullable<long> TCKimlikNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string BabaAdi { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Adresi { get; set; }
        public Nullable<long> Telefon { get; set; }
        public string AdSoyad { get; set; }
    }
}
