//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komutanliklar
    {
        public Komutanliklar()
        {
            this.MuzekkereIcmalDefteri = new HashSet<MuzekkereIcmalDefteri>();
            this.OlaylarBilgisi = new HashSet<OlaylarBilgisi>();
        }
    
        public int Id { get; set; }
        public string Komutanlik { get; set; }
    
        public virtual ICollection<MuzekkereIcmalDefteri> MuzekkereIcmalDefteri { get; set; }
        public virtual ICollection<OlaylarBilgisi> OlaylarBilgisi { get; set; }
    }
}
