//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlayYerleri
    {
        public OlayYerleri()
        {
            this.DaimiArastirmaTutanaklari = new HashSet<DaimiArastirmaTutanaklari>();
            this.GelenEvrak = new HashSet<GelenEvrak>();
            this.GidenEvrak = new HashSet<GidenEvrak>();
            this.MuzekkereIcmalDefteri = new HashSet<MuzekkereIcmalDefteri>();
            this.OlaylarBilgisi = new HashSet<OlaylarBilgisi>();
        }
    
        public int Id { get; set; }
        public string OlayYeri { get; set; }
    
        public virtual ICollection<DaimiArastirmaTutanaklari> DaimiArastirmaTutanaklari { get; set; }
        public virtual ICollection<GelenEvrak> GelenEvrak { get; set; }
        public virtual ICollection<GidenEvrak> GidenEvrak { get; set; }
        public virtual ICollection<MuzekkereIcmalDefteri> MuzekkereIcmalDefteri { get; set; }
        public virtual ICollection<OlaylarBilgisi> OlaylarBilgisi { get; set; }
    }
}
