//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlaylarBilgisi
    {
        public long Id { get; set; }
        public long SiraNo { get; set; }
        public decimal OlayBilNo { get; set; }
        public System.DateTime OlayTarihi { get; set; }
        public int OlayYeriId { get; set; }
        public int OlayId { get; set; }
        public Nullable<int> KomutanlikId { get; set; }
        public Nullable<int> TansifId { get; set; }
    
        public virtual Komutanliklar Komutanliklar { get; set; }
        public virtual Suclar Suclar { get; set; }
        public virtual OlayYerleri OlayYerleri { get; set; }
        public virtual Tasnifler Tasnifler { get; set; }
    }
}
