//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subeler
    {
        public Subeler()
        {
            this.ArsivGelenGiden = new HashSet<ArsivGelenGiden>();
        }
    
        public int Id { get; set; }
        public string Sube { get; set; }
    
        public virtual ICollection<ArsivGelenGiden> ArsivGelenGiden { get; set; }
    }
}
