//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasnifler
    {
        public Tasnifler()
        {
            this.OlaylarBilgisi = new HashSet<OlaylarBilgisi>();
        }
    
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string AltBaslik { get; set; }
        public string Suc { get; set; }
        public string Grup { get; set; }
        public string KanunMaddesi { get; set; }
    
        public virtual ICollection<OlaylarBilgisi> OlaylarBilgisi { get; set; }
    }
}
