//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempOlaylar
    {
        public int Id { get; set; }
        public string val1 { get; set; }
        public string val2 { get; set; }
        public string val3 { get; set; }
        public string val4 { get; set; }
        public string val5 { get; set; }
        public string val6 { get; set; }
        public string val7 { get; set; }
        public string val8 { get; set; }
        public string val9 { get; set; }
        public string val10 { get; set; }
        public string val11 { get; set; }
        public string val12 { get; set; }
    }
}
