//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETS.VeriKatmani
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZimmetDefteri
    {
        public ZimmetDefteri()
        {
            this.GelenEvrak1 = new HashSet<GelenEvrak>();
            this.GidenEvrak1 = new HashSet<GidenEvrak>();
        }
    
        public long Id { get; set; }
        public long SiraNo { get; set; }
        public System.DateTime ZimmetTarihi { get; set; }
        public int TeslimAlanId { get; set; }
        public int KategoriId { get; set; }
        public Nullable<long> GelenEvrakId { get; set; }
        public Nullable<long> GidenEvrakId { get; set; }
    
        public virtual EvrakKategori EvrakKategori { get; set; }
        public virtual GelenEvrak GelenEvrak { get; set; }
        public virtual ICollection<GelenEvrak> GelenEvrak1 { get; set; }
        public virtual GidenEvrak GidenEvrak { get; set; }
        public virtual ICollection<GidenEvrak> GidenEvrak1 { get; set; }
        public virtual Personel Personel { get; set; }
    }
}
